default_config:

homeassistant:
  packages:
    card_entities: !include card_entities.yaml

# Enable frontend
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - http://localhost:4000/flightradar-flight-card.js

lovelace:
  mode: storage
  dashboards:
    lovelace-showcase:
      mode: yaml
      title: Showcase
      icon: mdi:mushroom
      show_in_sidebar: true
      filename: lovelace-showcase.yaml
