config:
history:

homeassistant:
  latitude: 34.2109109178703
  longitude: -77.88573674660009
  packages:
    card_entities: !include card_entities.yaml

# Enable frontend
frontend:
  extra_module_url:
    - http://localhost:4000/flightradar-flight-card.js

lovelace:
  mode: storage
  dashboards:
    lovelace-showcase:
      mode: yaml
      title: Showcase
      icon: mdi:mushroom
      show_in_sidebar: true
      filename: lovelace-showcase.yaml
